version: '3.2'

services:
  logstash:
    container_name: $CONTAINER_NAME
    build:
      context: "${PWD}"
      dockerfile: logstash.Dockerfile
      args:
        VERSION: $LOGSTASH_VERSION
    volumes:
      - type: bind
        source: "${PWD}/config/logstash.yml"
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: "${PWD}/pipeline"
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5001:5001/tcp"
      - "5001:5001/udp"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk-stack

networks:
  elk-stack:
    driver: bridge